# Generated by Django 4.1.5 on 2023-02-08 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="upload_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 9, 0, 20, 13, 719575)
            ),
        ),
    ]
