# Generated by Django 4.1.5 on 2023-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.FileField(upload_to="static/files_admin"),
        ),
    ]
