# Generated by Django 4.1.5 on 2023-02-08 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_file_upload_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
    ]
