# Generated by Django 4.1.5 on 2023-02-02 18:40

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_cmp_dot_alter_user_dot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmp",
            name="dot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.dot"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dot",
            field=models.ForeignKey(
                default=user.models.base_dot,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.dot",
            ),
        ),
    ]
